In [ ]:
import numpy as np

def perc(X,W,d):
  X = np.array(X)
  W = np.array(W)
  S = np.dot(X,W) #dot연산 : 내적, 선형결합
  if S>=d:
    return(1)
  else:
    return(0)

def perc_and(X):
  return(perc(X,[5,5],6))
def perc_or(X):
  return(perc(X,[5,5],4))
def perc_nand(X):
  return(1-perc_and(X))
def perc_xor(X):
  return(perc_and([perc_nand(X),perc_or(X)]))



for x in range(2):
  for y in range(2):
    print(perc_xor([x,y]))


0
1
1
0


In [ ]:
import numpy as np

def perc(X,W,d):
  X = np.array(X)
  W = np.array(W)
  S = np.dot(X,W) #dot연산 : 내적, 선형결합
  if S>=d:
    return(1)
  else:
    return(0)

for x in range(2):
  for y in range(2):
    print(perc([x,y],[5,5],2))

1
0
0
0


In [ ]:
import numpy as np

A = np.array([[0,1,1,1,0],
             [1,0,0,0,1],
             [1,0,0,1,1],
             [1,0,1,0,1],
             [1,1,0,0,1],
             [1,0,0,0,1],
             [0,1,1,1,0]])

B = np.array([[0,1,1,1,0],
             [1,0,0,0,1],
             [1,0,0,0,1],
             [0,1,1,1,0],
             [1,0,0,0,1],
             [1,0,0,0,1],
             [0,1,1,1,0]])

C = np.array([[0,1,1,1,0],
             [1,0,0,0,1],
             [1,0,0,0,1],
             [0,0,0,0,0],
             [1,0,0,0,1],
             [1,0,0,0,1],
             [0,1,1,1,0]])

D = np.array([[0, 1, 0, 1, 0],
              [1, 0, 1, 0, 1],
              [0, 1, 0, 1, 0],
              [1, 0, 1, 0, 1],
              [1, 0, 0, 0, 1],
              [0, 1, 0, 1, 0]])



#sum은 모든 성분의 합
np.sum(D)

#abs는 모든성분의 절댓값
np.abs(-D)


def H(X,Y):
  return(np.abs(np.sum(X-Y)))

def P(X,Y):
  return(np.sum(X*Y)/np.sum(X))

for X, i in enumerate([A,B,C]):
  #psrint(H(X,D),"해밍{}번째".format(i))
  print(P(X,C),"퍼셉트론{}번째".format(i))



14 [[0 1 1 1 0]
 [1 0 0 0 1]
 [1 0 0 1 1]
 [1 0 1 0 1]
 [1 1 0 0 1]
 [1 0 0 0 1]
 [0 1 1 1 0]]
16 [[0 1 1 1 0]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [0 1 1 1 0]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [0 1 1 1 0]]
46 [[0 1 1 1 0]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [0 0 0 0 0]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [0 1 1 1 0]]
